### ISSUE TITLE
import statements and python 3 compatibility

### ISSUE THREAD

**Issue by ZacDiggum** [morefigs/py-ic-imaging-control#12]
Hi there,

I'm using python 3.5 and I had to change all the import statements like this to make pyicic working:
`from this import that`
to
`from .this import that`
See also this [post](https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3) on stackoverflow.
Should I make a PR?

**Comment by morefigs** [comment]
Yes, please do!

**Comment by ZacDiggum** [comment]
I see @vascotenner already did all the work a couple of hours ago. :) Thanks, I'll close this issue.
