### ISSUE TITLE
installing pyicic

### ISSUE THREAD

**Issue by geedubs** [morefigs/py-ic-imaging-control#15]
Hi! Sorry for making this an issue, but I couldn't find an email or alternative contact. 

I'm following your installation instructions and I'm unsure how to "Install pyicic." I tried "pip install -U pyicic", but this fails because the package isn't on PyPI. 

pip is the only method I'm familiar with installing packages... Am I missing something?

**Comment by morefigs** [comment]
Yes, sorry there's no pip or even setup.py yet. You'll have to copy it manually somewhere. To get started quickly you could simply copy the files into your working directory.

**Comment by geedubs** [comment]
Thanks! I ended up realising this (soon after some googling). ;)
