### ISSUE TITLE
expose autofocus feature

### ISSUE THREAD

**Issue by ZacDiggum** [morefigs/py-ic-imaging-control#16]
Hi,
I've got a TIS camera featuring a 'one push' autofocus function that I'd like to use from within Python. The model no. is DFK AFUP031-M12. Could you give some advice on how to implement the autofocus into your wrapper?
Thanks...

**Comment by ZacDiggum** [comment]
Hi,
when I try to execute cam.focus_one_push() I get an AttributeError:

```
Traceback (most recent call last):
  File "eyebox_main.py", line 146, in process_frame
    self.cam.focus_one_push()
  File "C:\winpython\python-3.5.3.amd64\lib\site-packages\pyicic\IC_Camera.py",
line 55, in __getattr__
    raise AttributeError
AttributeError
```
:-(

**Comment by morefigs** [comment]
`__getattr__` should only be called if the attribute is not found on the class. Could you double check that the `focus_one_push` method is definitely in your camera class?

**Comment by ZacDiggum** [comment]
I had the wrapper installed in the wrong env... now it's working! Thank you so much!
