### ISSUE TITLE
How to know the absolute exposure time by using exposure.value? 

### ISSUE THREAD

**Issue by YongMa1988** [morefigs/py-ic-imaging-control#28]
I just want to know how to change the exposure time.
I found the exposure.value which is within the range of (-13,4). But what does the value range mean? For example, what is the absolute exposure time of -4?

**Comment by morefigs** [comment]
I believe it's different for different cameras, so I don't know the exact mapping. You could compare values to those in the proprietary configuration software.

**Comment by YongMa1988** [comment]
Thanks, from the IC capture software, the max and min exposure time are 1/1000 and 30 seconds.
So I guess the exposure time should be 2^exposure.value, at least it's close to that.
