### ISSUE TITLE
Comparison to official IC Imaging Control repository

### ISSUE THREAD

**Issue by orpinchasov** [morefigs/py-ic-imaging-control#34]
I just came across what seems to be an official repository for IC Imaging Source from TheImagingSource:
https://github.com/TheImagingSource/IC-Imaging-Control-Samples

I'm wondering if you're aware of its existence and whether there's an advantage of using py-ic-imaging-control instead of the official repository?

It seems that the first commit was on April 4th 2018. When I started using py-ic-imaging-control it didn't exist yet, so at the time py-ic-imaging-control was essential.

What do you think that should be done now?

**Comment by morefigs** [comment]
Thanks, I wasn't aware of that. I've added a note on this repo pointing to the official repo. I'm not sure of any advantages/differences between the two.
